services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: >-
      sh -c "yes | pnpm install --frozen-lockfile --prefer-offline && pnpm --filter web dev"
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://api:8000
    volumes:
      - ./:/app
      - web_node_modules:/app/node_modules
      - web_pnpm_store:/root/.local/share/pnpm
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 5
    tty: true
    stdin_open: true

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    working_dir: /app/apps/api
    command: uv run -- uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "${HOST_API_PORT:-8001}:8000"
    environment:
      API_HOST: 0.0.0.0
      API_PORT: 8000
    volumes:
      - ./:/app
      - api_venv:/app/apps/api/.venv
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 5s
      retries: 5
    tty: true
    stdin_open: true

volumes:
  web_node_modules:
  web_pnpm_store:
  api_venv:
