name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.12.2
          run_install: false

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.local/share/pnpm/store/v3
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install Node dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Add uv to PATH
        run: echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            apps/api/.venv
          key: ${{ runner.os }}-uv-${{ hashFiles('apps/api/pyproject.toml', 'apps/api/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Sync Python dependencies
        working-directory: apps/api
        run: uv sync --frozen

      - name: pnpm lint (web)
        run: pnpm lint:web

      - name: pnpm lint (biome)
        run: pnpm lint:repo

      - name: Ruff check
        working-directory: apps/api
        run: uv run -- ruff check

      - name: Pytest
        working-directory: apps/api
        run: uv run -- pytest
